<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntitiesFriendRequestProxy extends \Entities\FriendRequest implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setFromuid($fromuid)
    {
        $this->_load();
        return parent::setFromuid($fromuid);
    }

    public function getFromuid()
    {
        $this->_load();
        return parent::getFromuid();
    }

    public function setTouid($touid)
    {
        $this->_load();
        return parent::setTouid($touid);
    }

    public function getTouid()
    {
        $this->_load();
        return parent::getTouid();
    }

    public function setRequestTime($requestTime)
    {
        $this->_load();
        return parent::setRequestTime($requestTime);
    }

    public function getRequestTime()
    {
        $this->_load();
        return parent::getRequestTime();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'fromuid', 'touid', 'request_time');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}