<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntitiesPhotoProxy extends \Entities\Photo implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setPath($path)
    {
        $this->_load();
        return parent::setPath($path);
    }

    public function getPath()
    {
        $this->_load();
        return parent::getPath();
    }

    public function setDescription($description)
    {
        $this->_load();
        return parent::setDescription($description);
    }

    public function getDescription()
    {
        $this->_load();
        return parent::getDescription();
    }

    public function setUploaded($uploaded)
    {
        $this->_load();
        return parent::setUploaded($uploaded);
    }

    public function getUploaded()
    {
        $this->_load();
        return parent::getUploaded();
    }

    public function setPermission($permission)
    {
        $this->_load();
        return parent::setPermission($permission);
    }

    public function getPermission()
    {
        $this->_load();
        return parent::getPermission();
    }

    public function setLongtitude($longtitude)
    {
        $this->_load();
        return parent::setLongtitude($longtitude);
    }

    public function getLongtitude()
    {
        $this->_load();
        return parent::getLongtitude();
    }

    public function setLatitude($latitude)
    {
        $this->_load();
        return parent::setLatitude($latitude);
    }

    public function getLatitude()
    {
        $this->_load();
        return parent::getLatitude();
    }

    public function setUser(\Entities\User $user)
    {
        $this->_load();
        return parent::setUser($user);
    }

    public function getUser()
    {
        $this->_load();
        return parent::getUser();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'path', 'description', 'uploaded', 'permission', 'longtitude', 'latitude', 'user');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}