<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntitiesFriendRequestProxy extends \Entities\FriendRequest implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setRequestTime($requestTime)
    {
        $this->_load();
        return parent::setRequestTime($requestTime);
    }

    public function getRequestTime()
    {
        $this->_load();
        return parent::getRequestTime();
    }

    public function setComplete($complete)
    {
        $this->_load();
        return parent::setComplete($complete);
    }

    public function getComplete()
    {
        $this->_load();
        return parent::getComplete();
    }

    public function setFrom(\Entities\User $from)
    {
        $this->_load();
        return parent::setFrom($from);
    }

    public function getFrom()
    {
        $this->_load();
        return parent::getFrom();
    }

    public function setTo(\Entities\User $to)
    {
        $this->_load();
        return parent::setTo($to);
    }

    public function getTo()
    {
        $this->_load();
        return parent::getTo();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'request_time', 'complete', 'from', 'to');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}