<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntitiesUserProfileProxy extends \Entities\UserProfile implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setProfilePic($profilePic)
    {
        $this->_load();
        return parent::setProfilePic($profilePic);
    }

    public function getProfilePic()
    {
        $this->_load();
        return parent::getProfilePic();
    }

    public function setLocation($location)
    {
        $this->_load();
        return parent::setLocation($location);
    }

    public function getLocation()
    {
        $this->_load();
        return parent::getLocation();
    }

    public function setGender($gender)
    {
        $this->_load();
        return parent::setGender($gender);
    }

    public function getGender()
    {
        $this->_load();
        return parent::getGender();
    }

    public function setAbout($about)
    {
        $this->_load();
        return parent::setAbout($about);
    }

    public function getAbout()
    {
        $this->_load();
        return parent::getAbout();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'profile_pic', 'location', 'gender', 'about');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}